Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np

np.arange(0,9).reshape(3,3)

Create a 3x3 identity matrixCreate a 3x3 identity matrix


In [ ]:
np.ones(9).reshape(3,3)

Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand()np.random.rand()

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.normal(0,1,25)

Create the following matrix

In [ ]:
np.arange(0, 1, 0.01).reshape(10,10)

Create an array of 20 linearly spaced points between 0 and 1

In [ ]:
np.linspace(0,1,20)

Write a function that takes as input a 2-D ndarray and scales the last row and column by 2

In [114]:
def scale_br(arr):
    rows = arr.shape[0]
    columns = arr.shape[1]
    arr[rows-1] = arr[rows-1] * 2
    arr[:,columns-1] = arr[:,columns-1]  * 2
    return arr

a = np.arange(0,12).reshape(3,4)
scale_br(a)


array([[ 0,  1,  2,  6],
       [ 4,  5,  6, 14],
       [16, 18, 20, 44]])

Create a numpy array with 100 numbers from 1 to 20. You are not allowed to use any loop

In [115]:
np.random.randint(1,20, 100)

array([19, 16,  2, 13,  6, 17,  1, 12, 19, 19,  4, 14, 15, 16, 16, 17,  6,
        8, 18,  1,  2,  2, 18, 19,  9, 19, 19, 11, 19,  2,  7, 12,  6,  1,
       10, 18, 17,  4,  5,  4,  4, 14,  5,  4, 14,  4,  2,  8,  1, 15, 14,
       12, 14, 15,  4,  9, 14, 17,  1, 19,  9,  5,  8,  3, 17, 16,  6, 11,
        2, 11,  3,  2, 11,  9, 19,  2, 14, 15, 19, 16, 13, 12, 12,  1,  6,
       10, 10, 15,  9,  5,  1, 17,  3, 13, 17, 14, 19,  8,  7, 13])

Create a numpy array containing the sine of the numbers from the above array.

In [ ]:
np.sin( np.random.randint(1,20, 100) )

Compute the dot product of arrays 1,2,3,4 and cos(1),cos(2), cos(3), but first you have to reshape them into  2-dimensional arrays

In [116]:
a = np.array([1,2,3,4]).reshape(4,1)
b = np.cos([1,2,3]).reshape(1,3)
np.dot(a,b) # broadcasting

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 1.08060461, -0.83229367, -1.97998499],
       [ 1.62090692, -1.24844051, -2.96997749],
       [ 2.16120922, -1.66458735, -3.95996999]])

Create two (arbitrary) numpy arrays (3,3) - A, B

In [111]:
A = np.random.randint(1,20, (3,3))
B = np.arange(1,10, dtype=np.float64).reshape(3,3)
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Normalize the matrix B by adding a constant c that makes its minimum be equal to 0

In [112]:
# normalization by means of sum of all alements
B -= np.min(B) 
B /= B.sum()
B.sum()


1.0

Compute the transpose of A

In [117]:
A.T

array([[ 6,  7, 18],
       [ 7, 18, 19],
       [ 2,  4, 10]])

Compute the inverse of A. Use numpy.linalg

In [ ]:
np.linalg.inv(A) np.linalg.inv(A) 

Compute the determinant of A

In [118]:
np.linalg.det(A)

255.99999999999994

Solve the following equations:
X + 2Y = 3
3X + 4Y = 0

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([3,0])
np.linalg.solve(a,b)